### PR TITLE
File checksum retrieve call

### PR DESCRIPTION
**Pull request by ErykKul**
Hi,
I am using this library in [rdm-integration](https://github.com/libis/rdm-integration) project, where among other things, I need to compare the content between the source and the destination files. I have noticed that there exists a way of retrieving the checksum from IRods, but this client did not implement it yet. Since I need the checksum for easy change detection, I have implemented the call. Please let me know if you want me to change something before merging.
Thanks!

### CODE REVIEW

**Comment by trel** [comment]
Does this care / parse the checksum string at all?   Should it?

iRODS supports both MD5 and SHA256, with SHA256 as the default.

**Comment by ErykKul** [comment]
In my own code I use this:

```
func splitHash(checksum string) (string, string, error) {
	sp := strings.Split(checksum, ":")
	if len(sp) != 2 {
		return "", "", fmt.Errorf("unexpected checksum: %v", string(checksum))
	}
	hashType := sp[0]
	hash, err := base64.StdEncoding.DecodeString(sp[1])

	if hashType == "sha2" && len(hash) == 256/8 {
		hashType = types.SHA256
	} else if hashType == "sha2" && len(hash) == 512/8 {
		hashType = types.SHA512
	}
	return hashType, fmt.Sprintf("%x", hash), err
}
```

I can add this to the PR with extra check for MD5. If it is not one of three hashes, I would give an error. And maybe i.s.o. string, I would give a not encoded []byte. I will work something out and do the commit.

**Comment by ErykKul** [comment]
I have just added the commit for checksum string parsing. The hash type is a new go type with constants predefined, and the value is []byte, so you can easily encode it in any preferred way. The new signature of the checksum function:
```func Checksum(conn *connection.IRODSConnection, irodsPath string) (HashType, []byte, error)```

**Comment by iychoi** [comment]
Thanks for the MR, I'll review and merge soon!

**Pull request merged**
